language: android
android:
  components:
  - build-tools-22.0.1
  - build-tools-23.0.1
  - android-22
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository

before_install:
- chmod +x gradlew

script: "./gradlew clean build -PdisablePreDex"